<?xml version="1.0" encoding="utf-8"?><Database Name="fluffyUnicorns" Class="bookmarksDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=fluffyUnicorns.db.12042275.hostedresource.com;Initial Catalog=fluffyUnicorns;Persist Security Info=True;User ID=fluffyUnicorns" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="fluffyUnicornsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bookmarks" Member="bookmarks">
    <Type Name="bookmark">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fileName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fileData" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fileDescription" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="browser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="userID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.login" Member="logins">
    <Type Name="login">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>